### ISSUE TITLE
Default theme in settings.json

### ISSUE THREAD

**Issue by sunib** [ThumNet/MDoc#4]
At this moment it does not seem to be possible to configure a default theme in settings.json. Would that be nice?

**Comment by ThumNet** [comment]
Not yet documented, but try using ‘defaultTheme’

**Comment by sunib** [comment]
Already found it, but it was looking at my localstorage first. Check, solved.

**Comment by ThumNet** [comment]
When you have never set the theme manually the localstorage is never set, so the setting is used.
